title: IT Course Modules
description: A website for IT course modules (Python, HTML, Networking, etc.)
baseurl: "/it-course"  # because the site is in a subfolder of your GitHub Pages
url: "https://smithjackb.github.io"  # main domain, not the full subpath
theme: minima
markdown: kramdown
