title: IT Course Modules
description: A website for IT course modules (Python, HTML, Networking, etc.)
baseurl: "/it-course"  # required because your site is in a subfolder
url: "https://smithjackb.github.io"  # GitHub username domain only
theme: minima
markdown: kramdown
