title: IT Course Modules
description: A website for IT course modules (Python, HTML, Networking, etc.)

url: "https://smithjackb.github.io/it-course"  # GitHub username domain only
theme: minima
markdown: kramdown


title: IT Course Modules
description: A website for IT course modules (Python, HTML, Networking, etc.)
baseurl: "/it-course"  # required because your site is in a subfolder
url: "https://smithjackb.github.io"  # GitHub username domain only
theme: minima
markdown: kramdown

plugins:
  - jekyll-sitemap


---

### ✅ Instructions:
- Save this content in `it-course/java-8-features.md`.
- Add a link to it in your `index.md`:
  ```markdown
  - [Java 8 Features Deep Dive](/it-course/java-8-features/)
